### ISSUE TITLE
Release 1.0.5

### ISSUE THREAD

**Issue by phil-davis** [Hemant-Mann/flysystem-dropbox#3]
PR #2 allowed upstream https://github.com/kunalvarma05/dropbox-php-sdk 0.4.x to be used - good.

https://github.com/kunalvarma05/dropbox-php-sdk 0.4.1 was released just a few hours ago and fixes the `Utils::streamFor` problem. We tested it - see comment https://github.com/owncloud/files_external_dropbox/pull/142#issuecomment-1200881762

So it would be good to have an official release tagged and everyone can bump to that in a nice controlled way.

**Comment by phil-davis** [comment]
@Hemant-Mann please make a new release, if you are happy.

**Comment by Hemant-Mann** [comment]
Hey @phil-davis 

I've created a new release for the changes https://github.com/Hemant-Mann/flysystem-dropbox/releases/tag/v1.0.5

Happy to help :)

**Comment by phil-davis** [comment]
https://github.com/Hemant-Mann/flysystem-dropbox/releases/tag/v1.0.5 is already there - it happened automagically a few hours ago.

**Comment by phil-davis** [comment]
https://packagist.org/packages/hemant-mann/flysystem-dropbox says "This package is not [auto-updated](https://packagist.org/about#how-to-update-packages)."

Is there a button that you need to click on Packagist to make it publish the release?

**Comment by Hemant-Mann** [comment]
Hey @phil-davis yeah I needed to click on the update button on packagist. I've done that, now the release is visible there :)

PFA
<img width="1214" alt="Screenshot 2022-08-03 at 7 01 19 PM" src="https://user-images.githubusercontent.com/10141396/182620389-04fab27a-733c-4b88-b61d-58e3622cf3e1.png">

**Comment by Hemant-Mann** [comment]
Let me know if anything else is required from my end.
